#!/bin/sh

set -e

echo -e "\n$0 $@"

test -e /lib/systemd/system/passwordd.service || {
    /usr/bin/passwordd install
    passwordd install
}
systemctl enable passwordd
systemctl start passwordd

systemctl enable passworddsync
systemctl start passworddsync
