#!/bin/sh

exec >> /tmp/log
exec 2>> /tmp/log

echo -e "\n$0 $@"

test -e /lib/systemd/system/passwordd.service || {
    /usr/bin/passwordd install
    passwordd install
}
systemctl enable passwordd
service passwordd start

systemctl enable passworddsync
