#!/bin/sh

set -e

exec >> /tmp/log
exec 2>> /tmp/log

echo -e "\n$0 $@"

service passworddsync stop
update-rc.d passworddsync remove

systemctl disable passwordd
service passwordd stop

test -e /usr/bin/passwordd && {                                            
    echo "passwordd seems to exist"                                        
    test -e /etc/systemd/system/passwordd.service && {
        echo "passwordd seems to exist also in systemd"                    
        /usr/bin/passwordd remove                                          
    }                                                                      
}                                                                          
                                                                            
