#!/bin/sh

set -e

echo -e "\n$0 $@"

service passworddsync stop
update-rc.d passworddsync remove

systemctl disable passwordd
service passwordd stop

test -e /usr/bin/passwordd && {                                            
    echo "passwordd seems to exist"                                        
    test -e /lib/systemd/system/passwordd.service && {
        echo "passwordd seems to exist also in systemd"                    
        /usr/bin/passwordd remove  ||
            rm /lib/systemd/system/passwordd.service
    }                                                                      
}                                                                          
                                                                            
