#!/bin/bash

exec > /tmp/passwordd.log
exec 2> /tmp/passwordd.log
### BEGIN INIT INFO
# Provides:     passwordd
# Required-Start:	$networking
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	transfer passwords
### END INIT INFO

KEYS=""
PARAMS=""
test -e /etc/passworddsync.conf && . /etc/passworddsync.conf

case "\$1" in
  start)
      passwordd start
      passworddsync --pull $PARAMS $KEYS
      ;;
  stop)
      passworddsync --push $PARAMS $KEYS
      passwordd stop
      # Try giving some time for sending the mail
      sleep 1
      ;;
  restart)
      $0 stop
      $0 start
      ;;
  force-reload)
      $0 restart
esac

