#!/bin/bash

### BEGIN INIT INFO
# Provides:     passwordd
# Required-Start:	$networking
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	transfer passwords
### END INIT INFO

KEYS=""
PARAMS=""
HOSTS=""
MYHOSTNAME=`hostname -f`
test -e /etc/passworddsync.conf && . /etc/passworddsync.conf

case "$1" in
    start)
        [ -z "$HOSTS" ] && {
            passworddsync --pull $PARAMS $KEYS
        }
        [ -z "$HOSTS" ] || {
            for HOST in $HOSTS; do 
                [ x$MYHOSTNAME != x$HOST ] && {
                    ping -c 1 $HOST >/dev/null 2>&1 && {
                        passworddsync --pull $HOST $PARAMS $KEYS
                    }
                }
            done
        }
        ;;
    stop)
        [ -z "$HOSTS" ] && {
            passworddsync --push $PARAMS $KEYS
        }
        [ -z "$HOSTS" ] || {
            for HOST in $HOSTS; do 
                [ x$MYHOSTNAME != x$HOST ] && {
                    ping -c 1 $HOST >/dev/null 2>&1 && {
                        passworddsync --push $HOST $PARAMS $KEYS
                    }
                }
            done
        }
        # Try giving some time for sending the mail
        sleep 1
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        . /etc/passworddsync.conf; for i in $KEYS; do echo -n "$i: "; passwordc get $i; done
        ;;
    force-reload)
        $0 restart
esac

